s=set()
print("Creates empty set:",s)
s.add(2)
s.add(2)
s.add("Lavanya")
print("Remove duplicate elements and print:",s)
s.remove(2)
print("Remove 2 and returns:",s)
s.add(3)
print(s)
s.discard(30)
print("simply return list as there is no 30:",s)
s.pop()
print("randamly remove the elemnet:",s)
s.clear()
print(s)
s={1,2,3,4}
s1={3,4,5}
print("Union :",s.union(s1))
print("Intersection:",s.intersection(s1))
print("Difference:",s1.difference(s))
print("Symmetric difference:",s1.symmetric_difference(s))
